### ISSUE TITLE
Fix Dales interface examples

### ISSUE THREAD

**Issue by goord** [goord/dales#17]
Add a very trivial rico example
Add a less trivial asynchronous call example

For both examples, add a python script and jupyter notebook to the OMUSE dales directory.

**Comment by fjansson** [comment]
Also remove old examples that no longer work.

Place examples here: omuse/src/omuse/community/dales/example/
Bubble example already there. 

TODO: 
* add notebooks. Singularity image should find them, or copy into the image.
* more examples
* fix bubble example (make_bubble accesses global d.grids once)

**Comment by goord** [comment]
Fixed bubble and plotting example. Bubble example has jupyter notebook.
