### ISSUE TITLE
cross sections output + grid MPI inconsistent

### ISSUE THREAD

**Issue by fjansson** [goord/dales#6]
The cross section code has not been fully updated with the change from slab to grid parallellization.
`crossxz.x___y___.001.nc` is written only by process 0
`crossyz.x___y___.001.nc` is written by every process
This would be consistent with slab parallellization. 

We can easily let every process write both files, this gives more cross section data. I will do this for now in the thermodynamics branch. However the exact output then depends on the MPI geometry. Also, it takes more disk space than only a single xz/yz cross section.

**Comment by goord** [comment]
Has been fixed in dales by @fjansson
